name: mamba_tinystories_1M
vocab_size: 10000 #bpe vocab 
d_model: 64        # hidden size 64
n_layers: 8        # 8 layers ~1M params
seq_len: 256

#Mamba SSM
d_state: 16
d_conv: 3
expand: 2
pad_token_id: 0
dropout: 0.0

