model_dir: results/gpt2_medium/model
tokenizer_dir: results/gpt2_medium/tokenizer

prompts_file: data/prompts.txt
references_file: data/references.txt

max_gen_length: 128
device: mps        # oder "cpu" / "cuda"
batch_size: 4
num_examples: 100
out_json: eval_gpt2_medium.json
