#GPT-Neo-125M architecture
name: gpt2_medium
arch: gpt2_from_scratch
#tokenizer_config: configs/tokenizers/tinystories_10k.yaml
tokenizer_config: configs/tokenizers/tinystories_1M.yaml

# GPT-2 style architecture
n_layer: 12
n_head: 12
n_embd: 768
n_positions: 256
n_ctx: 256

# Optional defaults (safe)
dropout: 0.0
bias: true