name: gpt2_small
#arch: gpt2_from_scratch
model_config: configs/models/gpt2_small.yaml
tokenizer_config: configs/tokenizers/tinystories_8k.yaml

training_args:
  output_dir: ./results/gpt2_small
  overwrite_output_dir: true
  num_train_epochs: 5
  per_device_train_batch_size: 4
  per_device_eval_batch_size: 4
  evaluation_strategy: steps
  eval_steps: 500
  save_steps: 1000
  logging_steps: 100
  learning_rate: 5.0e-4
  warmup_steps: 200
  save_total_limit: 2
  fp16: false
  report_to: wandb